version: "3.7"
services:
  finance-manager:
    container_name: finance-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: admin
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: EDYRcmEpuF8
      DATABASE_NAME: finance
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: bash -c "uvicorn financesvc.main:app --reload --host 0.0.0.0 --port 8001"
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: finance
      POSTGRES_PASSWORD: EDYRcmEpuF8
    ports:
      - "35432:5432"
    restart: unless-stopped
    volumes:
      - pgdata_finance:/var/lib/postgresql/data

volumes:
  pgdata_finance:
