version: "3.7"
services:
  finance-manager:
    container_name: finance-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: admin
      DATABASE_PORT: 45432
      DATABASE_PASSWORD: EDYRcmEpuF8
      DATABASE_NAME: finance
      USER_CODE_LENGTH: 6
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: bash -c "uvicorn financesvc.main:app --reload --host 0.0.0.0 --port 8001"
    restart: unless-stopped